s = []
s.append("https://www.cnn.com/")
s.append("https://www.cnn.com/world")
s.append("https://www.cnn.com/india")
s.append("https://www.cnn.com/china")
print(s)
print(s.pop())
print(s.pop())
print(s)
print(s[-1])
